#!/usr/bin/env bash

BOTTOM=$(grep BOTTOM .env | cut -d '=' -f2 | cut -d '#' -f1)
echo

if [ $BOTTOM = "host" ]; then
  APP_PATH=$PWD
elif [ $BOTTOM = "machine" ]; then
  APP_PATH=${PWD/home/hosthome}
fi

docker run --rm -it \
  -e APP_PATH=${APP_PATH} \
  -e DB_PROTO=mongodb \
  -e DB_HOST=192.168.2.2 \
  -e DB_PORT=27017 \
  -e DB_NAME=dbName \
  -e DB_USER=root \
  -e DB_PASS=password \
  -e ITERATIONS=543 \
  -e HASH_DIGEST=sha512 \
  -e SECRET=gz2tN3ALtLPzFKnsOOjsK4m8c2cnwG3hGky8F1h3QaYAOmA4ulb5pA \
  -e AUTO_LOCKING=yes \
  -v ${APP_PATH}:/usr/src/app \
  -v ${APP_PATH}/.bash_history:/root/.bash_history \
  -w /usr/src/app \
  --network common \
  node:14.9.0-buster \
  npm $@

echo
echo
